export const ADMIN_UI = {
  portalTitle: 'BỆNH VIỆN QUÂN Y 87',
  portalSubtitle: 'Chương trình điểm danh',
  roleLabel: 'QUẢN TRỊ VIÊN',
  searchPlaceholder: 'Tìm Đơn vị, Nhân viên, vị trí...',
  searchPlaceholderStaff: 'Tìm nhân viên theo tên...',
  searchPlaceholderDepartments: 'Tìm theo tên, mã, vị trí...',
  support: 'Hỗ trợ',
  logout: 'Đăng xuất',
  footer: {
    copyright: '© 2026 BỆNH VIỆN QUÂN Y 87 — Chương trình điểm danh phát triển bởi Tham mưu - Hành chính',

  },

  bottomPanels: {
    forecast: {
      title: 'Dự báo quân số',
      description: 'Phân tích xu hướng điểm danh và quân số theo Đơn vị.',
      button: 'Phân tích xu hướng',
    },
    tools: {
      title: 'Công cụ quản trị',
      items: ['Báo cáo quân số', 'Nhật ký hệ thống', 'Phân quyền truy cập'],
    },
  },

  dashboard: {
    deptFilterLabel: 'Lọc theo Đơn vị',
    deptFilterAll: 'Tất cả Đơn vị',
    sendReminder: 'Gửi nhắc nhở',
    progressTitle: 'Tiến độ điểm danh',
    presenceTitle: 'Tỷ lệ hiện diện',
    kpiScopeHospital: 'Phạm vi: Toàn viện',
    kpiScopeDept: (deptLabel) => `Phạm vi: ${deptLabel}`,
    refreshDashboard: 'Làm mới',
    colActions: 'THAO TÁC',
    colDept: 'Đơn vị',
    colProgress: 'TIẾN ĐỘ',
    colRate: 'TỶ LỆ',
    colStatus: 'TRẠNG THÁI',
    reportStatusBlocked: 'Đã khóa gửi báo cáo — bấm để mở',
    reportStatusOpen: 'Cho phép gửi báo cáo — bấm để khóa',
    reportStatusSubmitted: 'Đã gửi báo cáo hôm nay',
    reportStatusProcessing: 'Đang xử lý...',
    lockStatusLocked: 'Đã khóa sổ — bấm để mở khóa',
    lockStatusManualLocked: 'Admin đã khóa sổ sớm — bấm để mở khóa',
    lockStatusOpen: 'Đang mở — bấm để khóa sổ',
    lockStatusUnlocked: 'Đã mở khóa đặc cách — bấm để khóa sổ lại',
    lockStatusProcessing: 'Đang xử lý...',
    completed: 'HOÀN THÀNH',
    incomplete: 'CHƯA XONG',
    kpiTotal: 'Tổng quân số',
    kpiPresent: 'Đi làm',
    kpiAbsent: 'Nghỉ phép',
    kpiStudy: 'Đi học',
    kpiDuty: 'Đi công tác',
    chartUnchecked: 'Chưa chấm',
    reminderModalTitle: 'Gửi nhắc nhở Điểm danh',
    reminderModalHint:
      'Nhắc nhở gửi tới tài khoản đăng nhập Trưởng phòng (HEAD). Gán Trưởng đơn vị ở màn Đơn vị chưa đủ — cần thêm tài khoản tại Phân quyền người dùng.',
    reminderReadyBadge: 'Sẵn sàng gửi',
    reminderNoHeadBadge: 'Chưa có tài khoản HEAD',
    reminderNoHeadHint:
      'Thêm tài khoản vai trò Trưởng phòng tại Cài đặt → Phân quyền người dùng, gắn nhân viên thuộc đơn vị này.',
    reminderSend: 'Gửi',
    reminderSelectAll: 'Chọn tất cả đơn vị có thể gửi',
    actionUnlock: 'Mở khóa chỉnh sửa',
    actionBlockReport: 'Khóa gửi báo cáo',
    actionUnblockReport: 'Mở khóa gửi báo cáo',
    blockReportReason: 'Khóa gửi báo cáo từ bảng điều khiển',
    noIncomplete: 'Tất cả ĐƠN VỊ đã hoàn thành điểm danh.',
    loading: 'Đang tải bảng điều khiển...',
    reminderHistoryTitle: 'Lịch sử gửi nhắc nhở',
    reminderFilterFrom: 'Từ ngày',
    reminderFilterTo: 'Đến ngày',
    reminderFilterRange: 'Ngày điểm danh',
    reminderApplyFilter: 'Tìm kiếm',
    reminderStatsTitle: 'Thống kê theo ĐƠN VỊ',
    reminderStatsTotalLabel: 'Tổng lần nhắc',
    reminderListTitle: 'CHI TIẾT',
    reminderStatsColDept: 'ĐƠN VỊ',
    reminderStatsColCount: 'SỐ LẦN NHẮC',
    reminderHistoryColDate: 'NGÀY Điểm danh',
    reminderHistoryColDept: 'ĐƠN VỊ',
    reminderHistoryColType: 'LOẠI',
    reminderHistoryColTime: 'THỜI GIAN GỬI',
    reminderHistoryEmpty: 'Không có dữ liệu!',
    reminderStatsEmpty: 'Không có dữ liệu!',
    reminderTriggerManual: 'Thủ công',
    reminderTriggerAuto: 'Tự động',
    reminderExportExcel: 'Xuất Excel',
    reminderHistoryExportSheet: 'Lịch sử nhắc nhở',
    reminderHistoryMobile: {
      searchPlaceholder: 'Tìm kiếm đơn vị...',
      filter: 'Bộ lọc',
      sentAtLabel: 'Gửi lúc:',
    },
    deptDetailSelectDept: 'Chọn ĐƠN VỊ',
    deptDetailSelectDate: 'Chọn ngày',
    deptDetailApplyFilter: 'Tìm kiếm',
    deptDetailExportReport: 'Xuất báo cáo',
    deptDetailLoading: 'Đang tải chi tiết điểm danh...',
    deptDetailEmpty: 'Không có dữ liệu!',
    deptDetailExportSheet: 'Chi tiết điểm danh',
    deptDetailExportFilename: 'chi-tiet-diem-danh.xlsx',
    deptDetailColStaff: 'nhân viên',
    deptDetailColEmpCode: 'MÃ NHÂN VIÊN',
    deptDetailColStatus: 'TRẠNG THÁI',
    deptDetailColNote: 'GHI CHÚ / LÝ DO',
    deptDetailShowing: (from, to, total) =>
      `Hiển thị ${from} - ${to} trên tổng số ${total} nhân viên`,
    deptDetailMobileTitle: 'Danh sách nhân viên',
    deptDetailMobileResultsCount: (total) => `${total} nhân viên`,
  },

  nav: {
    dashboard: 'Bảng điều khiển',
    dashboardOverview: 'Tổng quan chung',
    dashboardDeptDetail: 'Chi tiết Đơn vị',
    catalog: 'Danh mục hành chính',
    departments: 'Đơn vị',
    staff: 'Nhân viên',
    staffRanks: 'Cấp bậc',
    staffPositions: 'Chức vụ',
    statusCatalog: 'Trạng thái làm việc',
    utilities: 'Tiện ích',
    reminderHistory: 'Lịch sử gửi nhắc nhở',
    settings: 'Cài đặt',
    settingsSystem: 'Cài đặt hệ thống',
    settingsUsers: 'Phân quyền người dùng',
  },

  settings: {
    system: {
      groupSystemName: 'Tên hệ thống',
      groupBranding: 'Giao diện & thương hiệu',
      groupAttendanceLock: 'Thời gian chốt sổ & nhắc nhở',
      reminderTime: 'Giờ nhắc tự động',
      reminderTimeHint:
        'Hệ thống tự gửi nhắc nhở tới trưởng ban các phòng chưa hoàn thành điểm danh. Admin vẫn có thể gửi thủ công từ bảng điều khiển.',
      reminderTimeRequired: 'Giờ nhắc nhở không được để trống.',
      portalTitle: 'Tên hiển thị',
      logo: 'Logo hệ thống',
      logoSelected: 'Đã chọn logo',
      logoRemove: 'Xóa logo',
      loginAvatar: 'Ảnh nền đăng nhập',
      loginAvatarUpload: 'Tải ảnh nền đăng nhập',
      loginAvatarSelected: 'Đã chọn ảnh nền',
      loginAvatarRemove: 'Xóa ảnh nền đăng nhập',
      lockTime: 'Giờ chốt sổ',
      lockTimeHint:
        'Sau giờ này, trưởng ban không thể chỉnh sửa hoặc gửi báo cáo trên màn Điểm danh. Admin có thể mở khóa ngày nếu cần.',
      saving: 'Đang lưu...',
      titleRequired: 'Tên hệ thống không được để trống.',
      lockTimeRequired: 'Giờ chốt sổ không được để trống.',
    },
  },

  accounts: {
    newButton: 'Thêm tài khoản',
    searchPlaceholder: 'Tìm tên đăng nhập, họ tên, mã NV, phòng ...',
    searchPlaceholderMobile: 'Tìm theo tên, mã hoặc đơn vị...',
    roleFilterPlaceholder: 'Lọc theo vai trò...',
    statusFilterPlaceholder: 'Lọc theo trạng thái...',
    active: 'Đang hoạt động',
    inactive: 'Ngưng hoạt động',
    formTitleCreate: 'Thêm tài khoản',
    formTitleEdit: 'Cập nhật tài khoản',
    deleteTitle: 'Xóa tài khoản',
    deleteMessage: (username) =>
      `Bạn có chắc muốn xóa tài khoản "${username}"? Thao tác không thể hoàn tác.`,
    stats: {
      total: 'Tổng tài khoản',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
    },
    columns: {
      username: 'TÊN ĐĂNG NHẬP',
      empCode: 'MÃ NV',
      fullname: 'HỌ VÀ TÊN',
      role: 'VAI TRÒ',
      dept: 'Đơn vị',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    form: {
      username: 'Tên đăng nhập',
      password: 'Mật khẩu',
      passwordEditHint: 'Để trống nếu không đổi mật khẩu',
      fullname: 'Họ và tên',
      fullnameFromEmployee: 'Họ và tên (theo nhân viên)',
      role: 'Vai trò',
      employee: 'Nhân viên',
      employeeSelectPlaceholder: '— Chọn nhân viên trong danh mục —',
      employeeRequired: 'Vui lòng chọn nhân viên cho tài khoản Trưởng phòng',
      deptFromEmployee: 'Đơn vị (theo nhân viên)',
      headDeptTaken:
        'Đơn vị này đã có tài khoản Trưởng đơn vị. Vui lòng sửa hoặc xóa tài khoản hiện có trước khi tạo mới.',
      headDeptNote:
        'Mỗi đơn vị chỉ được một tài khoản Trưởng đơn vị. Muốn thay người, hãy sửa hoặc xóa tài khoản hiện có.',
    },
    resetPasswordTitle: 'Đặt lại mật khẩu',
    resetPasswordDesc: (fullname, username) =>
      `Đặt mật khẩu mới cho tài khoản "${fullname}" (${username}).`,
    resetPasswordConfirm: 'Xác nhận mật khẩu mới',
    resetPasswordSubmit: 'Đặt lại mật khẩu',
    resetPasswordMinLength: 'Mật khẩu mới phải có ít nhất 6 ký tự',
    resetPasswordMismatch: 'Xác nhận mật khẩu không khớp',
    resetPasswordAction: 'Đặt lại MK',
    mobile: {
      listTitle: (count) => `Tài khoản (${count})`,
      filter: 'Bộ lọc',
      filterRole: 'Vai trò',
      filterStatus: 'Trạng thái',
      filterAll: 'Tất cả',
      roleAdmin: 'Quản trị viên',
      roleHead: 'Trưởng đơn vị',
      edit: 'Sửa',
      resetPassword: 'Đặt lại MK',
      delete: 'Xóa',
    },
  },

  departments: {
    newButton: 'Thêm Đơn vị',
    manageGroupsButton: 'Quản lý nhóm',
    filter: 'Bộ lọc',
    groupFilterAll: 'Tất cả',
    groupFilterLabel: 'Lọc theo nhóm',
    groupFilterPlaceholder: 'Tìm theo khối...',
    stats: {
      totalDepts: 'Tổng Đơn vị',
      totalStaff: 'Tổng Nhân viên',
      avgStaff: 'Quân số TB/Đơn vị',
      efficiency: 'Tỷ lệ hoạt động',
    },
    columns: {
      code: 'MÃ Đơn vị',
      group: 'NHÓM',
      unitCode: 'MÃ đơn vị',
      name: 'TÊN Đơn vị',
      location: 'VỊ TRÍ',
      head: 'Trưởng đơn vị',
      staff: 'QUÂN SỐ',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm Đơn vị mới',
    formTitleEdit: 'Cập nhật Đơn vị',
    deleteTitle: 'Xóa Đơn vị',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa Đơn vị "${name}"? Thao tác không thể hoàn tác.`,
    locationMapTitle: 'Sơ đồ vị trí',
    locationMapEmpty: 'Chưa có sơ đồ vị trí',
    viewLocationMap: 'Xem sơ đồ vị trí',
    mobile: {
      statusActive: 'Hoạt động',
      statusDeleted: 'Đã xóa',
      statusEmpty: 'Chưa có nhân sự',
      headRole: 'Trưởng đơn vị',
      staffLabel: 'Nhân sự',
    },
  },

  departmentGroups: {
    manageTitle: 'Quản lý nhóm Đơn vị',
    newButton: 'Thêm nhóm',
    formTitleCreate: 'Thêm nhóm mới',
    formTitleEdit: 'Cập nhật nhóm',
    deleteTitle: 'Xóa nhóm',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa nhóm "${name}"? Chỉ xóa được khi nhóm không còn Đơn vị.`,
    columns: {
      code: 'MÃ NHÓM',
      name: 'TÊN NHÓM',
      sortOrder: 'THỨ TỰ',
      deptCount: 'SỐ ĐƠN VỊ',
      actions: 'THAO TÁC',
    },
    form: {
      groupName: 'Tên nhóm',
      sortOrder: 'Thứ tự sắp xếp',
      groupNameRequired: 'Tên nhóm là bắt buộc',
    },
    mobile: {
      codePrefix: 'MÃ',
      sortOrderLabel: 'Thứ tự',
      deptCountLabel: 'Số đơn vị',
    },
  },

  staff: {
    newButton: 'Thêm Nhân viên',
    filter: 'Bộ lọc',
    deptFilterAll: 'Tất cả Đơn vị',
    deptFilterLabel: 'Lọc theo Đơn vị',
    deptFilterPlaceholder: 'Tìm theo đơn vị...',
    stats: {
      totalStaff: 'Tổng Nhân viên',
      activeStaff: 'Đang hoạt động',
      totalDepts: 'Đơn vị',
      inactive: 'Ngưng hoạt động',
    },
    columns: {
      code: 'MÃ Nhân viên',
      name: 'HỌ VÀ TÊN',
      rank: 'CẤP BẬC',
      position: 'CHỨC VỤ',
      dept: 'Đơn vị',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm mới Nhân viên',
    formTitleEdit: 'Cập nhật Nhân viên',
    formSubtitleEditTransfer: 'Chỉnh sửa thông tin hồ sơ và điều chuyển nhân sự',
    formSaveChanges: 'Lưu thay đổi',
    basicSectionTitle: 'Thông tin cơ bản',
    deleteTitle: 'Xóa Nhân viên',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa Nhân viên "${name}"? Thao tác không thể hoàn tác.`,
    active: 'Đang hoạt động',
    inactive: 'Ngưng hoạt động',
    transferReason: 'Lý do',
    transferReasonPlaceholder: 'Nhập lý do luân chuyển Đơn vị...',
    transferReasonRequired: 'Vui lòng nhập lý do luân chuyển Đơn vị',
    transferHeadRevokeTitle: (deptLabel) =>
      `Nhân viên đang là Trưởng đơn vị tại ${deptLabel}`,
    transferHeadRevokeSummary: (deptLabel) =>
      `Khi luân chuyển sẽ gỡ Trưởng đơn vị ${deptLabel} và thu hồi quyền Điểm danh.`,
    transferHeadRevokeAccountLabel: 'Tài khoản đăng nhập:',
    transferHeadRevokeDetailsToggle: 'Xem chi tiết',
    transferHeadRevokeDetailsHide: 'Thu gọn',
    transferHeadRevokeHint: (deptLabel, username) => {
      const accountLine = username
        ? ` Tài khoản đăng nhập: ${username}.`
        : '';
      return `Khi luân chuyển, hệ thống sẽ gỡ Trưởng đơn vị ${deptLabel} và ngưng quyền Điểm danh Trưởng đơn vị.${accountLine} Đơn vị cũ cần được gán Trưởng đơn vị mới sau đó.`;
    },
    transferHeadRevokeHintBody: (deptLabel) =>
      `Khi luân chuyển, hệ thống sẽ gỡ Trưởng đơn vị ${deptLabel} và ngưng quyền Điểm danh Trưởng đơn vị. Đơn vị cũ cần được gán Trưởng đơn vị mới sau đó.`,
    transferHeadRevokeCheckbox: 'Thu hồi quyền Trưởng đơn vị tại đơn vị cũ',
    transferHeadRevokeRequired:
      'Vui lòng tick xác nhận thu hồi quyền Trưởng đơn vị tại đơn vị cũ',
    transferSectionTitle: 'Thông tin luân chuyển',
    transferHistoryView: 'Lịch sử',
    transferHistoryTitle: (name, code) => `Lịch sử luân chuyển — ${name} (${code})`,
    transferHistoryEmpty: 'Chưa có lịch sử luân chuyển Đơn vị',
    transferHistoryCurrent: 'Hiện tại',
    transferHistoryColumns: {
      dept: 'Đơn vị',
      fromDate: 'Từ ngày',
      toDate: 'Đến ngày',
      reason: 'Lý do',
      createdBy: 'Người ghi',
      createdAt: 'Thời điểm ghi',
    },
    mobile: {
      deptLabel: 'Đơn vị',
      rankLabel: 'Cấp bậc',
      view: 'Xem',
      edit: 'Sửa',
      delete: 'Xóa',
      avatar: 'Ảnh',
      changeAvatar: 'Đổi ảnh đại diện',
    },
  },

  catalog: {
    deleteBlockedStaff: (count) =>
      `Đang có ${count} nhân viên sử dụng — hãy Ngưng hoạt động thay vì xóa`,
    deleteBlockedDept: (count) =>
      `Đang có ${count} nhân viên — không thể xóa Đơn vị`,
    deleteBlockedGroup: (count) =>
      `Đang có ${count} đơn vị — không thể xóa nhóm`,
    deleteBlockedStatus: (count) =>
      `Đang có ${count} bản ghi điểm danh — hãy Ngưng hoạt động thay vì xóa`,
  },

  staffRanks: {
    newButton: 'Thêm cấp bậc',
    searchPlaceholder: 'Tìm theo mã, tên cấp bậc...',
    unitLabel: 'cấp bậc',
    active: 'Đang sử dụng',
    inactive: 'Ngưng sử dụng',
    stats: {
      total: 'Tổng cấp bậc',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
      inUse: 'Đang có nhân viên',
    },
    columns: {
      code: 'MÃ',
      name: 'TÊN CẤP BẬC',
      sort: 'THỨ TỰ',
      usage: 'NHÂN VIÊN',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm cấp bậc mới',
    formTitleEdit: 'Cập nhật cấp bậc',
    deleteTitle: 'Xóa cấp bậc',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa cấp bậc "${name}"? Chỉ xóa được khi không còn nhân viên sử dụng.`,
    form: {
      code: 'Mã cấp bậc',
      name: 'Tên cấp bậc',
      sortOrder: 'Thứ tự sắp xếp',
      active: 'Trạng thái sử dụng',
      nameRequired: 'Tên cấp bậc là bắt buộc',
    },
  },

  staffPositions: {
    newButton: 'Thêm chức vụ',
    searchPlaceholder: 'Tìm theo mã, tên chức vụ...',
    unitLabel: 'chức vụ',
    active: 'Đang sử dụng',
    inactive: 'Ngưng sử dụng',
    stats: {
      total: 'Tổng chức vụ',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
      inUse: 'Đang có nhân viên',
    },
    columns: {
      code: 'MÃ',
      name: 'TÊN CHỨC VỤ',
      sort: 'THỨ TỰ',
      usage: 'NHÂN VIÊN',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm chức vụ mới',
    formTitleEdit: 'Cập nhật chức vụ',
    deleteTitle: 'Xóa chức vụ',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa chức vụ "${name}"? Chỉ xóa được khi không còn nhân viên sử dụng.`,
    form: {
      code: 'Mã chức vụ',
      name: 'Tên chức vụ',
      sortOrder: 'Thứ tự sắp xếp',
      active: 'Trạng thái sử dụng',
      nameRequired: 'Tên chức vụ là bắt buộc',
    },
  },

  statusCatalog: {
    newButton: 'Thêm trạng thái',
    searchPlaceholder: 'Tìm theo mã, tên...',
    unitLabel: 'trạng thái',
    active: 'Đang sử dụng',
    inactive: 'Ngưng sử dụng',
    stats: {
      total: 'Tổng trạng thái',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
      inUse: 'Đang có bản ghi',
    },
    columns: {
      code: 'MÃ',
      label: 'TÊN HIỂN THỊ',
      badge: 'NHÃN BADGE',
      sort: 'THỨ TỰ',
      usage: 'SỬ DỤNG',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm trạng thái mới',
    formTitleEdit: 'Cập nhật trạng thái',
    deleteTitle: 'Xóa trạng thái',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa trạng thái "${name}"? Thao tác không thể hoàn tác.`,
    form: {
      code: 'Mã trạng thái',
      label: 'Tên hiển thị',
      badgeLabel: 'Nhãn badge',
      color: 'Màu hiển thị',
      icon: 'Biểu tượng',
      sortOrder: 'Thứ tự sắp xếp',
      active: 'Trạng thái sử dụng',
    },
  },

  form: {
    save: 'Lưu',
    cancel: 'Hủy',
    confirmDelete: 'Xóa',
    loadingCode: 'Đang lấy mã...',
    deptCode: 'Mã Đơn vị',
    groupCode: 'Nhóm Đơn vị',
    groupSelectPlaceholder: '— Chọn nhóm —',
    groupName: 'Tên nhóm',
    deptName: 'Tên Đơn vị',
    unitCode: 'Mã đơn vị (vd: C11)',
    location: 'Vị trí / Tòa nhà',
    headName: 'Tên Trưởng đơn vị',
    headSelectPlaceholder: '— Chọn Trưởng đơn vị —',
    headSelectHintCreate:
      'Thêm nhân viên vào Đơn vị trước, sau đó cấu hình Trưởng đơn vị khi chỉnh sửa.',
    empCode: 'Mã Nhân viên',
    fullname: 'Họ và tên',
    rank: 'Cấp bậc',
    position: 'Chức vụ',
    dept: 'Đơn vị',
    status: 'Trạng thái',
    avatar: 'Ảnh đại diện',
    avatarDropPrefix: 'Kéo thả ảnh vào đây hoặc',
    avatarBrowse: 'chọn tệp',
    avatarDropSuffix: 'để tải lên.',
    avatarFormats: 'JPG, PNG, GIF, WEBP',
    avatarMaxSize: 'Tối đa 5MB',
    avatarSelected: 'Đã chọn ảnh đại diện',
    avatarHint: '',
    avatarRemove: 'Xóa ảnh đại diện',
    locationImage: 'Ảnh sơ đồ vị trí',
    locationImageSelected: 'Đã chọn sơ đồ vị trí',
    locationImageHint: '',
    locationImageRemove: 'Xóa sơ đồ vị trí',
    locationPlaceholder: 'Tòa A, Tầng 2',
    fullnamePlaceholder: 'Nhập họ và tên đầy đủ',
    rankPlaceholder: 'Tìm hoặc chọn cấp bậc...',
    positionPlaceholder: 'Tìm hoặc chọn chức vụ...',
    selectClear: 'Xóa lựa chọn',
    selectEmpty: 'Không tìm thấy kết quả',
  },

  excel: {
    menuLabel: 'Tác vụ Excel',
    menuLabelShort: 'Excel',
    template: 'Excel mẫu',
    import: 'Import Excel',
    export: 'Xuất Excel',
    importing: 'Đang import...',
    importSuccess: (count) => `Đã import ${count} bản ghi thành công.`,
    importPartial: (success, fail) =>
      `Import hoàn tất: ${success} thành công, ${fail} lỗi.`,
    importFail: 'Không thể import từ file Excel.',
    importEmpty: 'File Excel không có dòng dữ liệu.',
    importInvalidFile: 'File Excel không đúng định dạng mẫu. Vui lòng Xuất Excel mẫu.',
  },

  loading: 'Đang tải dữ liệu...',
  empty: 'Không có dữ liệu',
  resetFilters: 'Xóa bộ lọc',
  showing: (from, to, total) => `Hiển thị ${from} - ${to} của ${total}`,

  flash: {
    deptCreateSuccess: 'Đã thêm Đơn vị thành công.',
    deptUpdateSuccess: 'Đã cập nhật Đơn vị thành công.',
    groupCreateSuccess: 'Đã thêm nhóm thành công.',
    groupUpdateSuccess: 'Đã cập nhật nhóm thành công.',
    groupDeleteSuccess: (name) => `Đã xóa nhóm "${name}" thành công.`,
    groupDeleteFail: 'Không thể xóa nhóm. Vui lòng thử lại.',
    deptDeleteSuccess: (name) => `Đã xóa "${name}" thành công.`,
    deptDeleteFail: 'Không thể xóa Đơn vị. Vui lòng thử lại.',
    staffCreateSuccess: 'Đã thêm Nhân viên thành công.',
    staffUpdateSuccess: 'Đã cập nhật Nhân viên thành công.',
    staffTransferHeadRevokeSuccess:
      'Đã luân chuyển Nhân viên và thu hồi quyền Trưởng đơn vị tại đơn vị cũ. Vui lòng gán Trưởng đơn vị mới cho đơn vị cũ.',
    staffDeleteSuccess: (name) => `Đã xóa Nhân viên "${name}" thành công.`,
    staffDeleteFail: 'Không thể xóa Nhân viên. Vui lòng thử lại.',
    statusCreateSuccess: 'Đã thêm trạng thái thành công.',
    statusUpdateSuccess: 'Đã cập nhật trạng thái thành công.',
    statusDeleteSuccess: (name) => `Đã xóa trạng thái "${name}" thành công.`,
    statusDeleteFail: 'Không thể xóa trạng thái. Vui lòng thử lại.',
    rankCreateSuccess: 'Đã thêm cấp bậc thành công.',
    rankUpdateSuccess: 'Đã cập nhật cấp bậc thành công.',
    rankDeleteSuccess: (name) => `Đã xóa cấp bậc "${name}" thành công.`,
    rankDeleteFail: 'Không thể xóa cấp bậc. Vui lòng thử lại.',
    positionCreateSuccess: 'Đã thêm chức vụ thành công.',
    positionUpdateSuccess: 'Đã cập nhật chức vụ thành công.',
    positionDeleteSuccess: (name) => `Đã xóa chức vụ "${name}" thành công.`,
    positionDeleteFail: 'Không thể xóa chức vụ. Vui lòng thử lại.',
    settingsSaveSuccess: 'Đã lưu cấu hình hệ thống thành công.',
    accountCreateSuccess: 'Đã thêm tài khoản thành công.',
    accountUpdateSuccess: 'Đã cập nhật tài khoản thành công.',
    accountDeleteSuccess: (username) => `Đã xóa tài khoản "${username}" thành công.`,
    accountDeleteFail: 'Không thể xóa tài khoản. Vui lòng thử lại.',
    accountResetPasswordSuccess: (username) => `Đã đặt lại mật khẩu cho "${username}" thành công.`,
    saveFail: 'Lưu thất bại. Vui lòng kiểm tra lại thông tin.',
  },
};

export * from './adminTabs';
export * from './adminFilters';
