export const ADMIN_UI = {
  portalTitle: 'BỆNH VIỆN QUÂN Y 87',
  portalSubtitle: 'Chương trình chấm công',
  roleLabel: 'QUẢN TRỊ VIÊN',
  searchPlaceholder: 'Tìm Đơn vị, Nhân viên, vị trí...',
  searchPlaceholderStaff: 'Tìm nhân viên theo tên...',
  searchPlaceholderDepartments: 'Tìm theo tên, mã, vị trí...',
  support: 'Hỗ trợ',
  logout: 'Đăng xuất',
  footer: {
    copyright: '© 2026 BỆNH VIỆN QUÂN Y 87 VER 1.0.0  — Chương trình chấm công phát triển bởi Tham mưu - Hành chính',

  },

  bottomPanels: {
    forecast: {
      title: 'Dự báo quân số',
      description: 'Phân tích xu hướng Chấm công và quân số theo Đơn vị.',
      button: 'Phân tích xu hướng',
    },
    tools: {
      title: 'Công cụ quản trị',
      items: ['Báo cáo quân số', 'Nhật ký hệ thống', 'Phân quyền truy cập'],
    },
  },

  dashboard: {
    deptFilterLabel: 'Lọc theo Đơn vị',
    deptFilterAll: 'Tất cả Đơn vị',
    sendReminder: 'Gửi nhắc nhở',
    progressTitle: 'Tiến độ Chấm công',
    presenceTitle: 'Tỷ lệ hiện diện',
    kpiScopeHospital: 'Phạm vi: Toàn viện',
    kpiScopeDept: (deptLabel) => `Phạm vi: ${deptLabel}`,
    refreshDashboard: 'Làm mới',
    colActions: 'THAO TÁC',
    colDept: 'Đơn vị',
    colProgress: 'TIẾN ĐỘ',
    colRate: 'TỶ LỆ',
    colStatus: 'TRẠNG THÁI',
    reportStatusBlocked: 'Đã khóa gửi báo cáo — bấm để mở',
    reportStatusOpen: 'Cho phép gửi báo cáo — bấm để khóa',
    reportStatusSubmitted: 'Lịch sử đã nộp (cũ)',
    reportStatusOpen: 'Đang mở',
    reportStatusBlocked: 'Đã khóa chỉnh sửa HEAD',
    reportStatusProcessing: 'Đang xử lý...',
    lockStatusLocked: 'Đã khóa sổ — bấm để mở khóa',
    lockStatusManualLocked: 'Admin đã khóa sổ sớm — bấm để mở khóa',
    lockStatusOpen: 'Đang mở — bấm để khóa sổ',
    lockStatusUnlocked: 'Đã mở khóa đặc cách — bấm để khóa sổ lại',
    lockStatusProcessing: 'Đang xử lý...',
    completed: 'HOÀN THÀNH',
    incomplete: 'CHƯA XONG',
    kpiTotal: 'Tổng quân số',
    kpiPresent: 'Đi làm',
    kpiAbsent: 'Nghỉ phép',
    kpiStudy: 'Đi học',
    kpiDuty: 'Đi công tác',
    chartUnchecked: 'Chưa chấm',
    reminderModalTitle: 'Gửi nhắc nhở Chấm công',
    reminderModalHint:
      'Nhắc nhở gửi tới tài khoản đăng nhập Trưởng phòng (HEAD). Gán Trưởng đơn vị ở màn Đơn vị chưa đủ — cần thêm tài khoản tại Phân quyền người dùng.',
    reminderReadyBadge: 'Sẵn sàng gửi',
    reminderNoHeadBadge: 'Chưa có tài khoản HEAD',
    reminderNoHeadHint:
      'Thêm tài khoản vai trò Trưởng phòng tại Cài đặt → Phân quyền người dùng, gắn nhân viên thuộc đơn vị này.',
    reminderSend: 'Gửi',
    reminderSelectAll: 'Chọn tất cả đơn vị có thể gửi',
    actionUnlock: 'Mở khóa chỉnh sửa',
    actionBlockReport: 'Khóa gửi báo cáo',
    actionUnblockReport: 'Mở khóa gửi báo cáo',
    blockReportReason: 'Khóa gửi báo cáo từ bảng điều khiển',
    noIncomplete: 'Tất cả ĐƠN VỊ đã hoàn thành Chấm công.',
    loading: 'Đang tải bảng điều khiển...',
    reminderHistoryTitle: 'Lịch sử gửi nhắc nhở',
    reminderFilterFrom: 'Từ ngày',
    reminderFilterTo: 'Đến ngày',
    reminderFilterRange: 'Ngày Chấm công',
    reminderApplyFilter: 'Tìm kiếm',
    reminderStatsTitle: 'Thống kê theo ĐƠN VỊ',
    reminderStatsTotalLabel: 'Tổng lần nhắc',
    reminderListTitle: 'CHI TIẾT',
    reminderStatsColDept: 'ĐƠN VỊ',
    reminderStatsColCount: 'SỐ LẦN NHẮC',
    reminderHistoryColDate: 'NGÀY Chấm công',
    reminderHistoryColDept: 'ĐƠN VỊ',
    reminderHistoryColType: 'LOẠI',
    reminderHistoryColTime: 'THỜI GIAN GỬI',
    reminderHistoryEmpty: 'Không có dữ liệu!',
    reminderStatsEmpty: 'Không có dữ liệu!',
    reminderTriggerManual: 'Thủ công',
    reminderTriggerAuto: 'Tự động',
    reminderExportExcel: 'Xuất Excel',
    reminderHistoryExportSheet: 'Lịch sử nhắc nhở',
    reminderHistoryMobile: {
      searchPlaceholder: 'Tìm kiếm đơn vị...',
      filter: 'Bộ lọc',
      sentAtLabel: 'Gửi lúc:',
    },
    deptDetailSelectDept: 'Chọn ĐƠN VỊ',
    deptDetailSelectDate: 'Chọn ngày',
    deptDetailApplyFilter: 'Tìm kiếm',
    deptDetailExportReport: 'Xuất báo cáo',
    deptDetailLoading: 'Đang tải chi tiết Chấm công...',
    deptDetailEmpty: 'Không có dữ liệu!',
    deptDetailExportSheet: 'Chi tiết Chấm công',
    deptDetailExportFilename: 'chi-tiet-diem-danh.xlsx',
    deptDetailColStaff: 'nhân viên',
    deptDetailColEmpCode: 'MÃ NHÂN VIÊN',
    deptDetailColCheckIn: 'GIỜ VÀO',
    deptDetailColCheckOut: 'GIỜ RA',
    deptDetailColTimes: 'GIỜ',
    deptDetailColMachine: 'MÁY',
    deptDetailColStatus: 'TRẠNG THÁI',
    deptDetailColNote: 'GHI CHÚ / LÝ DO',
    deptDetailColActions: 'THAO TÁC',
    deptDetailScanLogs: 'Chi tiết quét',
    fingerprintMenu: 'Vân tay',
    fingerprintMenuAria: 'Thao tác vân tay',
    fillTimesAction: 'Điền giờ',
    fillTimesTitle: 'Điền giờ vào / ra',
    fillTimesHint:
      'Chỉ nhập ô đang trống trong 4 mốc (vào sáng, ra trưa, vào chiều, ra chiều). Giờ đã có từ máy không bị ghi đè. Đủ 4 mốc thì tự gán Đi làm / Đi trễ / Về sớm theo cài đặt hệ thống.',
    fillTimesSubmit: 'Lưu giờ',
    fillTimesNeedOne: 'Nhập ít nhất một giờ đang trống.',
    fillTimesError: 'Không lưu được giờ.',
    fillTimesAlreadySet: 'Đã có',
    fillTimesPreviewTitle: 'Xem trước logic',
    fillTimesPreviewAuto: 'Tự động',
    fillTimesPreviewStatus: 'Trạng thái chuyên cần',
    fillTimesPreviewKeep: (label) => `Giữ nguyên ${label}`,
    fillTimesPreviewRuleC: (hm, cutoff) =>
      `Dựa trên giờ vào sáng: ${hm} (mốc đi trễ: ${cutoff || '07:05'})`,
    fillTimesPreviewNoIn: 'Chưa có giờ vào — chưa gán ĐI LÀM / ĐI TRỄ.',
    fillTimesPreviewUnchecked: 'CHƯA CHẤM',
    fillTimesLabelIn: 'GIỜ VÀO',
    fillTimesLabelOut: 'GIỜ RA',
    fillTimesLabelMorningIn: 'VÀO SÁNG',
    fillTimesLabelNoonOut: 'RA TRƯA',
    fillTimesLabelAfternoonIn: 'VÀO CHIỀU',
    fillTimesLabelAfternoonOut: 'RA CHIỀU',
    clearAttendanceAction: 'Đưa về chưa chấm',
    clearAttendanceTitle: 'Đưa về chưa chấm',
    clearAttendanceHint:
      'Xóa trạng thái và giờ vào/ra của ngày này. Lịch sử quét vân tay vẫn giữ. Cần nhập lý do (kể cả sau khi đã gửi báo cáo).',
    clearAttendanceAfterSubmitWarn:
      'Ngày này đã gửi báo cáo. Đưa về chưa chấm không hủy báo cáo đã nộp; máy chấm vẫn từ chối quét; quân số ngày có thể lệch báo cáo.',
    clearAttendanceReason: 'Lý do',
    clearAttendanceReasonPlaceholder: 'Nhập lý do can thiệp…',
    clearAttendanceSubmit: 'Xác nhận',
    clearAttendanceNeedReason: 'Vui lòng nhập lý do.',
    clearAttendanceError: 'Không đưa về chưa chấm được.',
    clearAttendanceSuccess: 'Đã đưa về chưa chấm.',
    deptDetailShowing: (from, to, total) =>
      `Hiển thị ${from} - ${to} trên tổng số ${total} nhân viên`,
    deptDetailMobileTitle: 'Danh sách nhân viên',
    deptDetailMobileResultsCount: (total) => `${total} nhân viên`,
  },

  nav: {
    dashboard: 'Bảng điều khiển',
    dashboardOverview: 'Tổng quan chung',
    dashboardDeptDetail: 'Chi tiết Đơn vị',
    catalog: 'Danh mục hành chính',
    departments: 'Đơn vị',
    staff: 'Nhân viên',
    staffRanks: 'Cấp bậc',
    staffPositions: 'Chức vụ',
    statusCatalog: 'Trạng thái làm việc',
    utilities: 'Tiện ích',
    reminderHistory: 'Lịch sử gửi nhắc nhở',
    settings: 'Cài đặt',
    settingsSystem: 'Cài đặt hệ thống',
    settingsUsers: 'Phân quyền người dùng',
    settingsFingerprintTokens: 'Quản lý token vân tay',
  },

  fingerprintTokens: {
    title: 'Quản lý token vân tay',
    hint: 'Phát hành token kiosk và PIN đăng ký cho từng đơn vị. Dán token + enroll.pin vào agent.properties trên máy Agent.',
    agentHint: 'Đổi khoa enroll: sửa kiosk.token trong agent.properties → restart Fingerprint Agent.',
    listTitle: 'Danh sách token',
    colDept: 'Đơn vị',
    colLabel: 'Nhãn',
    colToken: 'Token',
    colEnrollPin: 'PIN Đăng ký',
    colAgent: 'Agent',
    colStatus: 'Trạng thái',
    colCreated: 'Ngày tạo',
    colActions: 'Thao tác',
    agentOnline: 'Online',
    agentOffline: 'Offline',
    agentOnlineHint: 'Agent đang gửi heartbeat',
    agentOfflineHint: 'Không nhận heartbeat trong ~90 giây (Agent tắt / mất mạng)',
    tokenMissing: '—',
    tokenMissingHint: 'Token cũ chưa lưu plaintext. Bấm Xoay để cấp lại rồi copy.',
    pinMissing: '—',
    pinMissingHint: 'Chưa đặt PIN. Bấm Đặt PIN rồi copy vào enroll.pin trên Agent.',
    renameLabel: 'Đổi nhãn',
    renameLabelTitle: 'Đổi nhãn kiosk',
    renameLabelSubtitle: 'Chỉ đổi tên hiển thị. Token và PIN không thay đổi — không cần restart Agent.',
    renameLabelField: 'Nhãn',
    renameLabelRequired: 'Nhập nhãn (tối đa 100 ký tự).',
    renameLabelSubmit: 'Lưu nhãn',
    renameLabelSuccess: 'Đã cập nhật nhãn kiosk.',
    setPin: 'Đặt PIN',
    setPinTitle: 'Đặt PIN đăng ký vân tay',
    setPinSubtitle: 'PIN 4–8 chữ số. Copy vào agent.properties (enroll.pin) trên máy khoa.',
    setPinLabel: 'PIN đăng ký',
    setPinPlaceholder: 'Ví dụ: 8700',
    setPinRequired: 'Nhập PIN gồm 4–8 chữ số.',
    setPinSubmit: 'Lưu PIN',
    setPinSuccess: 'Đã lưu PIN đăng ký.',
    copyPin: 'Sao chép',
    statusActive: 'Đang dùng',
    statusRevoked: 'Đã thu hồi',
    issue: 'Phát hành token',
    issueTitle: 'Phát hành token kiosk',
    issueSubtitle: 'Token sẽ hiện trên danh sách để Admin copy vào agent.properties trên máy khoa.',
    deptLabel: 'Đơn vị',
    deptRequired: 'Chọn đơn vị.',
    labelOptional: 'Nhãn (tuỳ chọn)',
    labelPlaceholder: 'Ví dụ: Kiosk máy phòng KHTH',
    confirmIssue: 'Phát hành',
    cancel: 'Hủy',
    revoke: 'Thu hồi',
    revokeTitle: 'Thu hồi token',
    rotate: 'Xoay token',
    rotateTitle: 'Xoay token',
    confirmRevoke: 'Thu hồi token này? Agent đang dùng token sẽ mất kết nối ngay.',
    confirmRotate:
      'Token cũ sẽ bị thu hồi. Copy token mới vào agent.properties rồi restart Agent.',
    rotateSubmit: 'Xoay token',
    issuedTitle: 'Token mới — lưu vào Agent',
    issuedHint: 'Sao chép vào agent.properties (kiosk.token). Token cũng hiện trên danh sách khi đang dùng.',
    copy: 'Sao chép',
    copied: 'Đã sao chép',
    close: 'Đóng',
    empty: 'Chưa có token kiosk nào.',
    loading: 'Đang tải...',
    loadError: 'Không tải được danh sách token.',
    unitLabel: 'token',
    stats: {
      total: 'Tổng số token',
      active: 'Đang dùng',
      revoked: 'Đã thu hồi',
      online: 'Agent Online',
    },
  },

  settings: {
    system: {
      groupSystemName: 'Tên hệ thống',
      groupBranding: 'Giao diện & thương hiệu',
      groupAttendanceLock: 'Khóa mềm ngày công & nhắc thiếu dữ liệu',
      reminderTime: 'Giờ nhắc thiếu dữ liệu chấm công',
      reminderTimeHint:
        'Nhắc trưởng đơn vị các khoa còn thiếu giờ vào/ra hoặc chưa chấm (theo ngày hôm qua). Admin vẫn nhắc thủ công từ bảng điều khiển.',
      reminderTimeRequired: 'Giờ nhắc nhở không được để trống.',
      portalTitle: 'Tên hiển thị',
      logo: 'Logo hệ thống',
      logoSelected: 'Đã chọn logo',
      logoRemove: 'Xóa logo',
      loginAvatar: 'Ảnh nền đăng nhập',
      loginAvatarUpload: 'Tải ảnh nền đăng nhập',
      loginAvatarSelected: 'Đã chọn ảnh nền',
      loginAvatarRemove: 'Xóa ảnh nền đăng nhập',
      lockTime: 'Giờ khóa mềm ngày công',
      lockTimeHint:
        'Sau giờ này trưởng đơn vị không chỉnh sửa Chấm công ngày hôm nay. Admin vẫn điền giờ / clear. Không phải hạn nộp báo cáo.',
      saving: 'Đang lưu...',
      titleRequired: 'Tên hệ thống không được để trống.',
      lockTimeRequired: 'Giờ khóa mềm không được để trống.',
      groupWorkHours: 'Giờ làm việc hành chính',
      workHoursHint:
        'Mốc chuẩn dùng cho đi trễ / về sớm. Khung nhận quét do Midpoint quyết định — đổi ca chỉ cần sửa midpoint, không sửa code.',
      workHoursMilestoneTitle: 'Mốc chuẩn',
      workHoursMidpointTitle: 'Midpoint',
      workHoursGraceTitle: 'Grace (phút)',
      morningInOfficial: 'Vào sáng',
      noonOutOfficial: 'Ra trưa',
      afternoonInOfficial: 'Vào chiều',
      afternoonOutOfficial: 'Ra chiều',
      morningOpen: 'Giờ mở cửa sáng',
      midpoint1: 'Midpoint 1',
      midpointNoon: 'Midpoint trưa',
      midpoint2: 'Midpoint 2',
      dayClose: 'Giờ đóng cửa',
      lateGraceMinutes: 'Grace đi trễ',
      earlyGraceMinutes: 'Grace về sớm',
      lateGraceHint: 'Cho phép trễ đầu giờ mà không trừ công (mẫu 5 phút).',
      earlyGraceHint: 'Ra chiều trong khoảng này không tính về sớm.',
      windowPreview: 'Khung nhận quét',
      windowMorningIn: 'Vào sáng',
      windowNoonOut: 'Ra trưa',
      windowAfternoonIn: 'Vào chiều',
      windowAfternoonOut: 'Ra chiều',
      resetWorkHours: 'Đặt lại',
    },
  },

  accounts: {
    newButton: 'Thêm tài khoản',
    searchPlaceholder: 'Tìm tên đăng nhập, họ tên, mã NV, phòng ...',
    searchPlaceholderMobile: 'Tìm theo tên, mã hoặc đơn vị...',
    roleFilterPlaceholder: 'Lọc theo vai trò...',
    statusFilterPlaceholder: 'Lọc theo trạng thái...',
    active: 'Đang hoạt động',
    inactive: 'Ngưng hoạt động',
    formTitleCreate: 'Thêm tài khoản',
    formTitleEdit: 'Cập nhật tài khoản',
    deleteTitle: 'Xóa tài khoản',
    deleteMessage: (username) =>
      `Bạn có chắc muốn xóa tài khoản "${username}"? Thao tác không thể hoàn tác.`,
    stats: {
      total: 'Tổng tài khoản',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
    },
    columns: {
      username: 'TÊN ĐĂNG NHẬP',
      empCode: 'MÃ NV',
      fullname: 'HỌ VÀ TÊN',
      role: 'VAI TRÒ',
      dept: 'Đơn vị',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    form: {
      username: 'Tên đăng nhập',
      password: 'Mật khẩu',
      passwordEditHint: 'Để trống nếu không đổi mật khẩu',
      fullname: 'Họ và tên',
      fullnameFromEmployee: 'Họ và tên (theo nhân viên)',
      role: 'Vai trò',
      employee: 'Nhân viên',
      employeeSelectPlaceholder: '— Chọn nhân viên trong danh mục —',
      employeeRequired: 'Vui lòng chọn nhân viên cho tài khoản Trưởng phòng',
      deptFromEmployee: 'Đơn vị (theo nhân viên)',
      headDeptTaken:
        'Đơn vị này đã có tài khoản Trưởng đơn vị. Vui lòng sửa hoặc xóa tài khoản hiện có trước khi tạo mới.',
      headDeptNote:
        'Mỗi đơn vị chỉ được một tài khoản Trưởng đơn vị. Muốn thay người, hãy sửa hoặc xóa tài khoản hiện có.',
    },
    resetPasswordTitle: 'Đặt lại mật khẩu',
    resetPasswordDesc: (fullname, username) =>
      `Đặt mật khẩu mới cho tài khoản "${fullname}" (${username}).`,
    resetPasswordConfirm: 'Xác nhận mật khẩu mới',
    resetPasswordSubmit: 'Đặt lại mật khẩu',
    resetPasswordMinLength: 'Mật khẩu mới phải có ít nhất 6 ký tự',
    resetPasswordMismatch: 'Xác nhận mật khẩu không khớp',
    resetPasswordAction: 'Đặt lại MK',
    mobile: {
      listTitle: (count) => `Tài khoản (${count})`,
      filter: 'Bộ lọc',
      filterRole: 'Vai trò',
      filterStatus: 'Trạng thái',
      filterAll: 'Tất cả',
      roleAdmin: 'Quản trị viên',
      roleHead: 'Trưởng đơn vị',
      edit: 'Sửa',
      resetPassword: 'Đặt lại MK',
      delete: 'Xóa',
    },
  },

  departments: {
    newButton: 'Thêm Đơn vị',
    manageGroupsButton: 'Quản lý nhóm',
    filter: 'Bộ lọc',
    groupFilterAll: 'Tất cả',
    groupFilterLabel: 'Lọc theo nhóm',
    groupFilterPlaceholder: 'Tìm theo khối...',
    stats: {
      totalDepts: 'Tổng Đơn vị',
      totalStaff: 'Tổng Nhân viên',
      avgStaff: 'Quân số TB/Đơn vị',
      efficiency: 'Tỷ lệ hoạt động',
    },
    columns: {
      code: 'MÃ Đơn vị',
      group: 'NHÓM',
      unitCode: 'MÃ đơn vị',
      name: 'TÊN Đơn vị',
      location: 'VỊ TRÍ',
      head: 'Trưởng đơn vị',
      staff: 'QUÂN SỐ',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm Đơn vị mới',
    formTitleEdit: 'Cập nhật Đơn vị',
    deleteTitle: 'Xóa Đơn vị',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa Đơn vị "${name}"? Thao tác không thể hoàn tác.`,
    locationMapTitle: 'Sơ đồ vị trí',
    locationMapEmpty: 'Chưa có sơ đồ vị trí',
    viewLocationMap: 'Xem sơ đồ vị trí',
    mobile: {
      statusActive: 'Hoạt động',
      statusDeleted: 'Đã xóa',
      statusEmpty: 'Chưa có nhân sự',
      headRole: 'Trưởng đơn vị',
      staffLabel: 'Nhân sự',
    },
  },

  departmentGroups: {
    manageTitle: 'Quản lý nhóm Đơn vị',
    newButton: 'Thêm nhóm',
    formTitleCreate: 'Thêm nhóm mới',
    formTitleEdit: 'Cập nhật nhóm',
    deleteTitle: 'Xóa nhóm',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa nhóm "${name}"? Chỉ xóa được khi nhóm không còn Đơn vị.`,
    columns: {
      code: 'MÃ NHÓM',
      name: 'TÊN NHÓM',
      sortOrder: 'THỨ TỰ',
      deptCount: 'SỐ ĐƠN VỊ',
      actions: 'THAO TÁC',
    },
    form: {
      groupName: 'Tên nhóm',
      sortOrder: 'Thứ tự sắp xếp',
      groupNameRequired: 'Tên nhóm là bắt buộc',
    },
    mobile: {
      codePrefix: 'MÃ',
      sortOrderLabel: 'Thứ tự',
      deptCountLabel: 'Số đơn vị',
    },
  },

  staff: {
    newButton: 'Thêm Nhân viên',
    filter: 'Bộ lọc',
    deptFilterAll: 'Tất cả Đơn vị',
    deptFilterLabel: 'Lọc theo Đơn vị',
    deptFilterPlaceholder: 'Tìm theo đơn vị...',
    stats: {
      totalStaff: 'Tổng Nhân viên',
      activeStaff: 'Đang hoạt động',
      totalDepts: 'Đơn vị',
      inactive: 'Ngưng hoạt động',
    },
    columns: {
      code: 'MÃ Nhân viên',
      name: 'HỌ VÀ TÊN',
      rank: 'CẤP BẬC',
      position: 'CHỨC VỤ',
      dept: 'Đơn vị',
      status: 'TRẠNG THÁI',
      fingerprint: 'VÂN TAY',
      actions: 'THAO TÁC',
    },
    fingerprintRegistered: 'Đã đăng ký',
    fingerprintMissing: 'Chưa đăng ký',
    fingerprintLabelFallback: 'Đã đăng ký',
    fingerprintDeleteLabel: 'Xóa vân tay',
    fingerprintDeleteTitle: 'Xóa đăng ký vân tay',
    fingerprintDeleteMessage: (name, fingerLabel) =>
      fingerLabel
        ? `Bạn có chắc muốn xóa đăng ký vân tay (${fingerLabel}) của "${name}"? Nhân viên cần đăng ký lại trên Agent.`
        : `Bạn có chắc muốn xóa đăng ký vân tay của "${name}"? Nhân viên cần đăng ký lại trên Agent.`,
    formTitleCreate: 'Thêm mới Nhân viên',
    formTitleEdit: 'Cập nhật Nhân viên',
    formSubtitleEditTransfer: 'Chỉnh sửa thông tin hồ sơ và điều chuyển nhân sự',
    formSaveChanges: 'Lưu thay đổi',
    basicSectionTitle: 'Thông tin cơ bản',
    deleteTitle: 'Xóa Nhân viên',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa Nhân viên "${name}"? Thao tác không thể hoàn tác.`,
    active: 'Đang hoạt động',
    inactive: 'Ngưng hoạt động',
    transferReason: 'Lý do',
    transferReasonPlaceholder: 'Nhập lý do luân chuyển Đơn vị...',
    transferReasonRequired: 'Vui lòng nhập lý do luân chuyển Đơn vị',
    transferHeadRevokeTitle: (deptLabel) =>
      `Nhân viên đang là Trưởng đơn vị tại ${deptLabel}`,
    transferHeadRevokeSummary: (deptLabel) =>
      `Khi luân chuyển sẽ gỡ Trưởng đơn vị ${deptLabel} và thu hồi quyền Chấm công.`,
    transferHeadRevokeAccountLabel: 'Tài khoản đăng nhập:',
    transferHeadRevokeDetailsToggle: 'Xem chi tiết',
    transferHeadRevokeDetailsHide: 'Thu gọn',
    transferHeadRevokeHint: (deptLabel, username) => {
      const accountLine = username
        ? ` Tài khoản đăng nhập: ${username}.`
        : '';
      return `Khi luân chuyển, hệ thống sẽ gỡ Trưởng đơn vị ${deptLabel} và ngưng quyền Chấm công Trưởng đơn vị.${accountLine} Đơn vị cũ cần được gán Trưởng đơn vị mới sau đó.`;
    },
    transferHeadRevokeHintBody: (deptLabel) =>
      `Khi luân chuyển, hệ thống sẽ gỡ Trưởng đơn vị ${deptLabel} và ngưng quyền Chấm công Trưởng đơn vị. Đơn vị cũ cần được gán Trưởng đơn vị mới sau đó.`,
    transferHeadRevokeCheckbox: 'Thu hồi quyền Trưởng đơn vị tại đơn vị cũ',
    transferHeadRevokeRequired:
      'Vui lòng tick xác nhận thu hồi quyền Trưởng đơn vị tại đơn vị cũ',
    transferSectionTitle: 'Thông tin luân chuyển',
    transferDeptAction: 'Chuyển đơn vị',
    transferDeptModalTitle: 'Chuyển đơn vị làm việc',
    transferDeptModalSubtitle: (name, code) => `${name} (${code})`,
    transferDeptFromLabel: 'Đơn vị hiện tại',
    transferDeptToLabel: 'Đơn vị đích',
    transferDeptSubmit: 'Xác nhận chuyển',
    transferDeptFingerprintHint:
      'Vân tay đã đăng ký vẫn dùng được tại mọi máy quét sau khi chuyển đơn vị.',
    transferHistoryView: 'Lịch sử',
    transferHistoryTitle: (name, code) => `Lịch sử luân chuyển — ${name} (${code})`,
    transferHistoryEmpty: 'Chưa có lịch sử luân chuyển Đơn vị',
    transferHistoryCurrent: 'Hiện tại',
    transferHistoryInitial: 'Gán ban đầu',
    transferHistoryColumns: {
      fromDept: 'Từ đơn vị',
      toDept: 'Đến đơn vị',
      fromDate: 'Từ ngày',
      toDate: 'Đến ngày',
      reason: 'Lý do',
      createdBy: 'Người ghi',
      createdAt: 'Thời điểm ghi',
    },
    mobile: {
      deptLabel: 'Đơn vị',
      rankLabel: 'Cấp bậc',
      view: 'Xem',
      edit: 'Sửa',
      delete: 'Xóa',
      avatar: 'Ảnh',
      changeAvatar: 'Đổi ảnh đại diện',
    },
  },

  catalog: {
    deleteBlockedStaff: (count) =>
      `Đang có ${count} nhân viên sử dụng — hãy Ngưng hoạt động thay vì xóa`,
    deleteBlockedDept: (count) =>
      `Đang có ${count} nhân viên — không thể xóa Đơn vị`,
    deleteBlockedGroup: (count) =>
      `Đang có ${count} đơn vị — không thể xóa nhóm`,
    deleteBlockedStatus: (count) =>
      `Đang có ${count} bản ghi Chấm công — hãy Ngưng hoạt động thay vì xóa`,
  },

  staffRanks: {
    newButton: 'Thêm cấp bậc',
    searchPlaceholder: 'Tìm theo mã, tên cấp bậc...',
    unitLabel: 'cấp bậc',
    active: 'Đang sử dụng',
    inactive: 'Ngưng sử dụng',
    stats: {
      total: 'Tổng cấp bậc',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
      inUse: 'Đang có nhân viên',
    },
    columns: {
      code: 'MÃ',
      name: 'TÊN CẤP BẬC',
      sort: 'THỨ TỰ',
      usage: 'NHÂN VIÊN',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm cấp bậc mới',
    formTitleEdit: 'Cập nhật cấp bậc',
    deleteTitle: 'Xóa cấp bậc',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa cấp bậc "${name}"? Chỉ xóa được khi không còn nhân viên sử dụng.`,
    form: {
      code: 'Mã cấp bậc',
      name: 'Tên cấp bậc',
      sortOrder: 'Thứ tự sắp xếp',
      active: 'Trạng thái sử dụng',
      nameRequired: 'Tên cấp bậc là bắt buộc',
    },
  },

  staffPositions: {
    newButton: 'Thêm chức vụ',
    searchPlaceholder: 'Tìm theo mã, tên chức vụ...',
    unitLabel: 'chức vụ',
    active: 'Đang sử dụng',
    inactive: 'Ngưng sử dụng',
    stats: {
      total: 'Tổng chức vụ',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
      inUse: 'Đang có nhân viên',
    },
    columns: {
      code: 'MÃ',
      name: 'TÊN CHỨC VỤ',
      sort: 'THỨ TỰ',
      usage: 'NHÂN VIÊN',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm chức vụ mới',
    formTitleEdit: 'Cập nhật chức vụ',
    deleteTitle: 'Xóa chức vụ',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa chức vụ "${name}"? Chỉ xóa được khi không còn nhân viên sử dụng.`,
    form: {
      code: 'Mã chức vụ',
      name: 'Tên chức vụ',
      sortOrder: 'Thứ tự sắp xếp',
      active: 'Trạng thái sử dụng',
      nameRequired: 'Tên chức vụ là bắt buộc',
    },
  },

  statusCatalog: {
    newButton: 'Thêm trạng thái',
    searchPlaceholder: 'Tìm theo mã, tên...',
    unitLabel: 'trạng thái',
    active: 'Đang sử dụng',
    inactive: 'Ngưng sử dụng',
    stats: {
      total: 'Tổng trạng thái',
      active: 'Đang sử dụng',
      inactive: 'Ngưng sử dụng',
      inUse: 'Đang có bản ghi',
    },
    columns: {
      code: 'MÃ',
      label: 'TÊN HIỂN THỊ',
      badge: 'NHÃN BADGE',
      sort: 'THỨ TỰ',
      usage: 'SỬ DỤNG',
      status: 'TRẠNG THÁI',
      actions: 'THAO TÁC',
    },
    formTitleCreate: 'Thêm trạng thái mới',
    formTitleEdit: 'Cập nhật trạng thái',
    deleteTitle: 'Xóa trạng thái',
    deleteMessage: (name) =>
      `Bạn có chắc muốn xóa trạng thái "${name}"? Thao tác không thể hoàn tác.`,
    form: {
      code: 'Mã trạng thái',
      label: 'Tên hiển thị',
      badgeLabel: 'Nhãn badge',
      color: 'Màu hiển thị',
      icon: 'Biểu tượng',
      sortOrder: 'Thứ tự sắp xếp',
      active: 'Trạng thái sử dụng',
      manualAllowed: 'Cho phép chấm thủ công',
      groupParent: 'Là trạng thái cha',
      parentCode: 'Trạng thái cha',
      parentCodePlaceholder: '— Chọn trạng thái cha —',
    },
  },

  form: {
    save: 'Lưu',
    cancel: 'Hủy',
    confirmDelete: 'Xóa',
    loadingCode: 'Đang lấy mã...',
    deptCode: 'Mã Đơn vị',
    groupCode: 'Nhóm Đơn vị',
    groupSelectPlaceholder: '— Chọn nhóm —',
    groupName: 'Tên nhóm',
    deptName: 'Tên Đơn vị',
    unitCode: 'Mã đơn vị (vd: C11)',
    location: 'Vị trí / Tòa nhà',
    headName: 'Tên Trưởng đơn vị',
    headSelectPlaceholder: '— Chọn Trưởng đơn vị —',
    headSelectHintCreate:
      'Thêm nhân viên vào Đơn vị trước, sau đó cấu hình Trưởng đơn vị khi chỉnh sửa.',
    empCode: 'Mã Nhân viên',
    fullname: 'Họ và tên',
    rank: 'Cấp bậc',
    position: 'Chức vụ',
    dept: 'Đơn vị',
    status: 'Trạng thái',
    avatar: 'Ảnh đại diện',
    avatarDropPrefix: 'Kéo thả ảnh vào đây hoặc',
    avatarBrowse: 'chọn tệp',
    avatarDropSuffix: 'để tải lên.',
    avatarFormats: 'JPG, PNG, GIF, WEBP',
    avatarMaxSize: 'Tối đa 5MB',
    avatarSelected: 'Đã chọn ảnh đại diện',
    avatarHint: '',
    avatarRemove: 'Xóa ảnh đại diện',
    locationImage: 'Ảnh sơ đồ vị trí',
    locationImageSelected: 'Đã chọn sơ đồ vị trí',
    locationImageHint: '',
    locationImageRemove: 'Xóa sơ đồ vị trí',
    locationPlaceholder: 'Tòa A, Tầng 2',
    fullnamePlaceholder: 'Nhập họ và tên đầy đủ',
    rankPlaceholder: 'Tìm hoặc chọn cấp bậc...',
    positionPlaceholder: 'Tìm hoặc chọn chức vụ...',
    selectClear: 'Xóa lựa chọn',
    selectEmpty: 'Không tìm thấy kết quả',
  },

  excel: {
    menuLabel: 'Tác vụ Excel',
    menuLabelShort: 'Excel',
    template: 'Excel mẫu',
    import: 'Import Excel',
    export: 'Xuất Excel',
    importing: 'Đang import...',
    importSuccess: (count) => `Đã import ${count} bản ghi thành công.`,
    importPartial: (success, fail) =>
      `Import hoàn tất: ${success} thành công, ${fail} lỗi.`,
    importFail: 'Không thể import từ file Excel.',
    importEmpty: 'File Excel không có dòng dữ liệu.',
    importInvalidFile: 'File Excel không đúng định dạng mẫu. Vui lòng Xuất Excel mẫu.',
  },

  loading: 'Đang tải dữ liệu...',
  empty: 'Không có dữ liệu',
  resetFilters: 'Xóa bộ lọc',
  showing: (from, to, total) => `Hiển thị ${from} - ${to} của ${total}`,

  flash: {
    deptCreateSuccess: 'Đã thêm Đơn vị thành công.',
    deptUpdateSuccess: 'Đã cập nhật Đơn vị thành công.',
    groupCreateSuccess: 'Đã thêm nhóm thành công.',
    groupUpdateSuccess: 'Đã cập nhật nhóm thành công.',
    groupDeleteSuccess: (name) => `Đã xóa nhóm "${name}" thành công.`,
    groupDeleteFail: 'Không thể xóa nhóm. Vui lòng thử lại.',
    deptDeleteSuccess: (name) => `Đã xóa "${name}" thành công.`,
    deptDeleteFail: 'Không thể xóa Đơn vị. Vui lòng thử lại.',
    staffCreateSuccess: 'Đã thêm Nhân viên thành công.',
    staffUpdateSuccess: 'Đã cập nhật Nhân viên thành công.',
    staffTransferHeadRevokeSuccess:
      'Đã luân chuyển Nhân viên và thu hồi quyền Trưởng đơn vị tại đơn vị cũ. Vui lòng gán Trưởng đơn vị mới cho đơn vị cũ.',
    staffTransferDeptSuccess:
      'Đã chuyển đơn vị. Vân tay vẫn dùng được tại mọi máy quét.',
    staffDeleteSuccess: (name) => `Đã xóa Nhân viên "${name}" thành công.`,
    staffDeleteFail: 'Không thể xóa Nhân viên. Vui lòng thử lại.',
    fingerprintDeleteSuccess: (name) => `Đã xóa đăng ký vân tay của "${name}".`,
    fingerprintDeleteFail: 'Không thể xóa đăng ký vân tay. Vui lòng thử lại.',
    statusCreateSuccess: 'Đã thêm trạng thái thành công.',
    statusUpdateSuccess: 'Đã cập nhật trạng thái thành công.',
    statusDeleteSuccess: (name) => `Đã xóa trạng thái "${name}" thành công.`,
    statusDeleteFail: 'Không thể xóa trạng thái. Vui lòng thử lại.',
    rankCreateSuccess: 'Đã thêm cấp bậc thành công.',
    rankUpdateSuccess: 'Đã cập nhật cấp bậc thành công.',
    rankDeleteSuccess: (name) => `Đã xóa cấp bậc "${name}" thành công.`,
    rankDeleteFail: 'Không thể xóa cấp bậc. Vui lòng thử lại.',
    positionCreateSuccess: 'Đã thêm chức vụ thành công.',
    positionUpdateSuccess: 'Đã cập nhật chức vụ thành công.',
    positionDeleteSuccess: (name) => `Đã xóa chức vụ "${name}" thành công.`,
    positionDeleteFail: 'Không thể xóa chức vụ. Vui lòng thử lại.',
    settingsSaveSuccess: 'Đã lưu cấu hình hệ thống thành công.',
    accountCreateSuccess: 'Đã thêm tài khoản thành công.',
    accountUpdateSuccess: 'Đã cập nhật tài khoản thành công.',
    accountDeleteSuccess: (username) => `Đã xóa tài khoản "${username}" thành công.`,
    accountDeleteFail: 'Không thể xóa tài khoản. Vui lòng thử lại.',
    accountResetPasswordSuccess: (username) => `Đã đặt lại mật khẩu cho "${username}" thành công.`,
    saveFail: 'Lưu thất bại. Vui lòng kiểm tra lại thông tin.',
  },
};

export * from './adminTabs';
export * from './adminFilters';
