export const AI_ASSISTANT_UI = {
  title: 'Trợ lý AI',
  placeholder: 'Nhập yêu cầu cho AI...',
  sendLabel: 'Gửi',
  closeLabel: 'Đóng trợ lý AI',
  thinking: 'Đang xử lý...',
  errorGeneric: 'Không thể kết nối Trợ lý AI. Vui lòng thử lại.',
  quickActions: [
    { id: 'work_status_report', label: 'Báo cáo trạng thái làm việc' },
    { id: 'attendance_status_report', label: 'Báo cáo trạng thái Điểm danh' },
    { id: 'batch_reminders', label: 'Gửi nhắc nhở Điểm danh' },
  ],
  widgets: {
    downloadTitle: 'Tải xuống báo cáo Excel',
    downloadButton: 'Tải xuống Excel',
    timeRangeTitle: 'Chọn khoảng thời gian',
    timeRangeFrom: 'Từ ngày',
    timeRangeTo: 'Đến ngày',
    timeRangeSubmit: 'Xem báo cáo',
    datePickerTitle: 'Chọn ngày Điểm danh',
    datePickerSubmit: 'Xuất báo cáo',
    pendingTitle: 'ĐƠN VỊ CHƯA XONG (chưa báo cáo)',
    pendingEmpty: 'Tất cả ĐƠN VỊ đã hoàn thành Điểm danh.',
    pendingReminderCta: 'Gửi nhắc nhở ngay',
    statusReportTitle: 'Báo cáo trạng thái làm việc',
    attendanceReportTitle: 'Báo cáo trạng thái Điểm danh',
    colDept: 'Đơn vị',
    colPresent: 'Đi làm',
    colLeave: 'Nghỉ phép',
    colStudy: 'Đi học',
    colDuty: 'Công tác',
    colUnchecked: 'Chưa chấm',
    colProgress: 'Tiến độ',
    colStatus: 'Trạng thái',
    reminderTitle: 'Xác nhận gửi nhắc nhở',
    reminderHint: 'Các ĐƠN VỊ CHƯA XONG điểm danh hôm nay:',
    reminderSelectAll: 'Chọn tất cả',
    reminderCancel: 'Hủy',
    reminderConfirm: 'Xác nhận gửi',
    reminderSending: 'Đang gửi...',
    reminderEmpty: 'Không có ĐƠN VỊ nào cần nhắc nhở.',
  },
};
