export const AI_ASSISTANT_UI = {
  title: 'Trợ lý AI',
  placeholder: 'Nhập yêu cầu cho AI...',
  sendLabel: 'Gửi',
  closeLabel: 'Đóng trợ lý AI',
  thinking: 'Đang xử lý...',
  errorGeneric: 'Không thể kết nối Trợ lý AI. Vui lòng thử lại.',
  quickActions: [
    { id: 'work_status_report', label: 'Báo cáo trạng thái làm việc' },
    { id: 'attendance_status_report', label: 'Báo cáo trạng thái Chấm công' },
    { id: 'remind_missing_punch_depts', label: 'Nhắc thiếu dữ liệu chấm công' },
  ],
  widgets: {
    downloadTitle: 'Tải xuống báo cáo Excel',
    downloadButton: 'Tải xuống Excel',
    timeRangeTitle: 'Chọn khoảng thời gian',
    timeRangeFrom: 'Từ ngày',
    timeRangeTo: 'Đến ngày',
    timeRangeSubmit: 'Xem báo cáo',
    datePickerTitle: 'Chọn ngày Chấm công',
    datePickerSubmit: 'Xuất báo cáo',
    pendingTitle: 'ĐƠN VỊ còn thiếu dữ liệu chấm công',
    pendingEmpty: 'Không có ĐƠN VỊ nào còn thiếu dữ liệu chấm công.',
    pendingReminderCta: 'Gửi nhắc nhở ngay',
    pendingReminderPrompt:
      'Bạn có muốn gửi nhắc nhở đến các ĐƠN VỊ còn thiếu dữ liệu chấm công không?',
    statusReportTitle: 'Báo cáo trạng thái làm việc',
    attendanceReportTitle: 'Báo cáo trạng thái Chấm công',
    colDept: 'Đơn vị',
    colPresent: 'Đi làm',
    colLeave: 'Nghỉ phép',
    colStudy: 'Đi học',
    colDuty: 'Công tác',
    colUnchecked: 'Chưa chấm',
    colProgress: 'Tiến độ',
    colStatus: 'Trạng thái',
    reminderTitle: 'Xác nhận gửi nhắc nhở',
    reminderHintPrefix: 'Các ĐƠN VỊ còn thiếu dữ liệu chấm công',
    reminderHintDefaultYesterday: ' (mặc định ngày hôm qua)',
    reminderSelectAll: 'Chọn tất cả',
    reminderCancel: 'Hủy',
    reminderConfirm: 'Xác nhận gửi',
    reminderSending: 'Đang gửi...',
    reminderEmpty: 'Không có ĐƠN VỊ nào cần nhắc nhở.',
  },
};
