export const STATUS_CATALOG_COLOR_OPTIONS = [
  { value: 'green', label: 'Xanh lá (Đi làm)' },
  { value: 'red', label: 'Đỏ (Nghỉ phép)' },
  { value: 'yellow', label: 'Vàng (Đi học)' },
  { value: 'blue', label: 'Xanh dương (Công tác)' },
  { value: 'teal', label: 'Xanh ngọc' },
  { value: 'amber', label: 'Cam' },
  { value: 'purple', label: 'Tím' },
  { value: 'pink', label: 'Hồng' },
  { value: 'brown', label: 'Nâu' },
  { value: 'gray', label: 'Xám' },
  { value: 'black', label: 'Đen' },
  { value: 'lime', label: 'Xanh chanh' },
  { value: 'cyan', label: 'Xanh cyan' },
  { value: 'indigo', label: 'Xanh chàm' },
];


export const STATUS_CATALOG_ICON_OPTIONS = [
  { value: 'check', label: 'Có mặt' },
  { value: 'x', label: 'Vắng' },
  { value: 'graduation', label: 'Đi học' },
  { value: 'briefcase', label: 'Công tác' },
  { value: 'clock', label: 'Đồng hồ' },
  { value: 'plane', label: 'Máy bay' },
  { value: 'baby', label: 'Thai sản' },
  { value: 'sick', label: 'Nghỉ ốm' },
  { value: 'late', label: 'Đi trễ' },
  { value: 'moon', label: 'Trực đêm nghỉ' },
  { value: 'home', label: 'Nghỉ tại nhà' },
  { value: 'pending', label: 'Chờ' },
  { value: 'coffee', label: 'Giải lao' },
  { value: 'car', label: 'Đi công việc ngoài' },
  { value: 'hospital', label: 'Đi khám bệnh' },
  { value: 'train', label: 'Đi công tác xa' },
  { value: 'sun', label: 'Ca sáng' },
  { value: 'star', label: 'Ca đặc biệt' },
  { value: 'shield', label: 'Bảo vệ' },
  { value: 'tools', label: 'Sửa chữa' },
];

